# Generated by Django 5.1.2 on 2024-10-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('date_posted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
